In [1]:
import numpy as np
import xarray as xr
import pickle
import pandas as pd
import time
import os

import datetime
from sys import getsizeof,path


import matplotlib.pyplot as plt
import matplotlib

import theano
import theano.tensor as tt
from theano.printing import pydotprint
import pymc3 as pm
theano.config.optimizer="fast_run"

In [29]:
a = np.arange(1,1+6*3*2).reshape(6,3,2)
b = np.arange(51,51+3*4*4).reshape(3,4,4)



a = xr.DataArray(a,dims=("age","BL","sex"),coords={"sex":["m","f"],"age":[2,3,4,5,6,7],"BL":["A","B","C"]})
b = xr.DataArray(b,dims=("sex","age","week"),coords={"sex":["f","u","m"],"age":[1,2,3,6],"week":[11,13,14,18]})

ta = tt.cast(a.values,"int64")

#print(a)
#print(b)

#print(a.indexes)

#print(ta[[0,1],[1,1]].eval())

print(a.coords)
print(b.coords)

print(a.dims,b.dims)

print(a)
print(b)



Coordinates:
  * sex      (sex) <U1 'm' 'f'
  * age      (age) int64 2 3 4 5 6 7
  * BL       (BL) <U1 'A' 'B' 'C'
Coordinates:
  * sex      (sex) <U1 'f' 'u' 'm'
  * age      (age) int64 1 2 3 6
  * week     (week) int64 11 13 14 18
('age', 'BL', 'sex') ('sex', 'age', 'week')
<xarray.DataArray (age: 6, BL: 3, sex: 2)>
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36]]])
Coordinates:
  * sex      (sex) <U1 'm' 'f'
  * age      (age) int64 2 3 4 5 6 7
  * BL       (BL) <U1 'A' 'B' 'C'
<xarray.DataArray (sex: 3, age: 4, week: 4)>
array([[[51, 52, 53, 54],
        [55, 56, 57, 58],
        [59, 60, 61, 62],
        [63, 64, 65, 66]],

       [[67, 68, 69, 70],
        [71, 72, 73, 74],
        [75, 76, 77, 78],

In [30]:
def IndexProperties(x):
    try:
        steps = np.diff(x)
        stepsizes = len(set(steps))
    
        return {"countable":True,"continous":stepsizes==1,"stepsize":min(steps)}
    except:
        return {"countable":False}

def IndexMap(x,common):
    return np.array([(a in common) for a in x ])

x = np.array([1,2,3,4,8,9])
print(IndexProperties(x))

print(IndexMap(np.array([0,1,2,3]),x))

{'countable': True, 'continous': False, 'stepsize': 1}
[False  True  True  True]


In [52]:
def IndexSumToMatch(X,iX,iC,dims,axis,sum_dir="skip"):
    """ 
        X,iX tensor and index along axis
        iC common index
        dims,axis number of dimensions and axis
        sum_dir skip, left or right """
    slice_blueprint = [slice(None) for n in range(dims)]
    slice_blueprint[axis] = 0
    
    z = tt.zeros_like(X[slice_blueprint])
    
    print("sum_dir",sum_dir)
    print(slice_blueprint)
    print(z.eval())
    
    nc,start,n_skipped = 0,0,0
    s = z
    
    print("common",iC,"axis",iX)
    
    for nx,ix in enumerate(iX):
        
        # The algorithm is not right.
        
        """ if nx != 0 and nc < len(iC):
            if iC[nc] < ix:
                print(iC[nc],ix)
                slice_blueprint[axis] = nx
                print(slice_blueprint,nx)
                x_skipped = X[slice_blueprint]
                s += x_skipped
                n_skipped += 1
                print("skip",x_skipped.eval(),s.eval(),n_skipped)
                
            else:
                if sum_dir == "skip":
                    s = z
                    
                    
                print("match",s.eval(),n_skipped,"pos",nx,nc)
                s = z
                start = nx
                nc += 1
                n_skipped = 0
        else:
            if iC[nc] < ix:
                start = nx
                nc += 1"""
    
    return X

In [53]:
"""
ModelParams keeps track of coordinate-ranges for Model-internal datasets

"""


class ModelParams(object):
    def __init__(self,coords={}):
        self.coords = coords
        
        self.params = {}
        
    def AddParam(self,param):
        
        pname = param.name
        if pname not in self.params.keys():
            self.params[pname] = param
        else:
            print("Param %s already exists",pname)
            
    def __getitem(self,name):
        return self.params.get(name,None)
    
    def Overlap(self):
        pass

class ModelParam(object):
    """ Everything is a parameter in a bayesian model """
    def __init__(self,name,coords,param,is_variable=True):
        
        self.name = name
        self.coords = coords
        self.param = param
        
    def Dims(self):
        return list(self.coords.keys())
        
    def DimIndex(self,dim_name):
        return self.Dims().index(dim_name)
        
    def Overlap(self,other,sum_missing=[]):
        """ Returns overlap of both params,
            returns A overlap with B, B with A, Common coords
        """
        dims,other_dims = self.Dims(),other.Dims()
        dimS,other_dimS = set(dims),set(other_dims)
        
        dim_overlap = dimS.intersection(other_dimS)
        overlap,other_overlap = self.param, other.param
        if len(dim_overlap) > 0:
            # figure non-matching dimensions, sum over non-matching dimensions
            not_in,other_not_in = dimS-other_dimS,other_dimS-dimS
            not_index,other_not_index = list(map(self.DimIndex,not_in)),list(map(other.DimIndex,other_not_in))
            if len(not_in) > 0:
                overlap = overlap.sum(axis=not_index)
                for k in not_in:
                    dims.remove(k)
            if len(other_not_in) > 0:
                other_overlap = other_overlap.sum(axis=other_not_index)
                for k in other_not_in:
                    other_dims.remove(k) # dims, other_dims are the new indices
            
            # Transpose matching dimensions
            other_transpose = list(map(other_dims.index,dims))
            other_overlap = other_overlap.dimshuffle(other_transpose)
            
            # Reduce coordinates for both theano objects
            overlap_index = {k:self.coords[k] for k in dims}
            other_index = {other_dims[i]:other.coords[other_dims[i]] for i in other_transpose}
            
            # Do the nasty stuff
            A,B,common_index = self.Overlap_Axes(overlap,other_overlap,overlap_index,other_index,sum_missing)
            return A,B,common_index
        else:
            return None,None,None
        
    def Overlap_Axes(self,A,B,A_index,B_index,sum_missing=[]):
        """ Returns theano objects A,B
        
            For each axis, compare indizes and slice inputs A,B to match each other
        """
        
        A_indexer,B_indexer,common_index = [],[],{}
        for axis,dim in enumerate(A_index.keys()):
            iA,iB = A_index[dim], B_index[dim] 
            print(axis)
            print(iA,iB)
            print(sorted(set(iA).union(set(iB))))
            
            iC = np.array(sorted( set(iA).intersection(set(iB)) ))
            common_index[dim] = iC
            
            iPA,iPB = IndexProperties(iA),IndexProperties(iB)
            A_sum, B_sum = "right","right"
            
            if iPA["countable"] == iPB["countable"] and iPA["countable"] == False:
                # Simple case for non-countable indices, only skipping with a boolean mask
                A_indexer.append(IndexMap(iA,iC))
                B_indexer.append(IndexMap(iB,iC))
                
            else: # more complex case, might involve skipping/summing of elements
                iPC = IndexProperties(iC) 
                print(iPA,iPB,iPC)
                
                if iPC["continous"] == True:
                    if iPC["stepsize"] == iPA["stepsize"]:
                        A_indexer.append( slice(iA.index(iC[0],iA.index(iC[-1])+1)) )
                    else:
                        A = IndexSumToMatch(A,iA,iC,len(A_index.keys()),axis,A_sum)
                        A_indexer.append(slice(None))

                    if iPC["stepsize"] == iPB["stepsize"]:
                        B_indexer.append( slice(iB.index(iC[0],iB.index(iC[-1])+1)) )
                    else:
                        B = IndexSumToMatch(B,iB,iC,len(B_index.keys()),axis,B_sum)
                        B_indexer.append(slice(None))
                        
                else: # involves skipping/summing in A and/or B
                    
                    print(axis,iPC)
                    print("\nA",iA)
                    A = IndexSumToMatch(A,iA,iC,len(A_index.keys()),axis,A_sum)
                    A_indexer.append(slice(None))
                    print("\nB",iB)
                    B = IndexSumToMatch(B,iB,iC,len(B_index.keys()),axis,B_sum)
                    B_indexer.append(slice(None))
                    
        
        return A[A_indexer],B[B_indexer],common_index        

class ObservedData(ModelParam):
    def __init__(self,name,data):
        """ data : xarray"""
        coords = {} # xarray.DataArray.coords is not properly ordered.
        for d in data.dims:
            coords[d] = sorted(data.coords[d].values) # Make sure indices are sorted as well.
        param = theano.shared(data.sel(coords).values)
        super(ObservedData,self).__init__(name,coords,param,is_variable=False)
        
        
    

In [54]:
o1 = ObservedData("by_sex_BL_age",a)

o2 = ObservedData("by_sex_age_week",b)


ov1,ov2,ocoords = o1.Overlap(o2)
print("coords:",ocoords)



od1 = ov1.eval()
od2 = ov2.eval()

print(od1.shape)
print(od2.shape)

print(od1)

print(od2)


0
[2, 3, 4, 5, 6, 7] [1, 2, 3, 6]
[1, 2, 3, 4, 5, 6, 7]
{'countable': True, 'continous': True, 'stepsize': 1} {'countable': True, 'continous': False, 'stepsize': 1} {'countable': True, 'continous': False, 'stepsize': 1}
0 {'countable': True, 'continous': False, 'stepsize': 1}

A [2, 3, 4, 5, 6, 7]
sum_dir right
[0, slice(None, None, None)]
[0 0]
common [2 3 6] axis [2, 3, 4, 5, 6, 7]
2 3
[1, slice(None, None, None)] 1
skip [30 27] [30 27] 1
2 4
[2, slice(None, None, None)] 2
skip [48 45] [78 72] 2
2 5
[3, slice(None, None, None)] 3
skip [66 63] [144 135] 3
2 6
[4, slice(None, None, None)] 4
skip [84 81] [228 216] 4
2 7
[5, slice(None, None, None)] 5
skip [102  99] [330 315] 5

B [1, 2, 3, 6]
sum_dir right
[0, slice(None, None, None)]
[0 0 0]
common [2 3 6] axis [1, 2, 3, 6]
match [0 0 0] 0 pos 1 0
match [0 0 0] 0 pos 2 1
match [0 0 0] 0 pos 3 2
1
['f', 'm'] ['f', 'm', 'u']
['f', 'm', 'u']
coords: {'age': array([2, 3, 6]), 'sex': array(['f', 'm'], dtype='<U1')}
(6, 2)
(4, 2)
[[ 12   9]


In [42]:
def Overlap(a,b):
    """
        - trivial case: both Parameters have the same dimensions and indexes along those dimensions (coords)
        - same indexes, but different dimensions: sum over unique dimensions
        - missing indexes: either leave out (sex,BL) or try to sum in more fine grained (temporal,week)
    
    """
   
    ksa,ksb = set(a.dims),set(b.dims)
    
    sa,sb = a.sum(ksa-ksb),b.sum(ksb-ksa)
    
    print(ksa,ksb)
    print(ksa-ksb)
    print(ksb-ksa)
    
    print(sa)
    print(sb)
#    a.coords
    
Overlap(a,b)    

{'sex', 'BL', 'age'} {'week', 'sex', 'age'}
{'BL'}
{'week'}
<xarray.DataArray (age: 6, sex: 2)>
array([[  9,  12],
       [ 27,  30],
       [ 45,  48],
       [ 63,  66],
       [ 81,  84],
       [ 99, 102]])
Coordinates:
  * sex      (sex) <U1 'm' 'f'
  * age      (age) int64 2 3 4 5 6 7
<xarray.DataArray (sex: 3, age: 4)>
array([[210, 226, 242, 258],
       [274, 290, 306, 322],
       [338, 354, 370, 386]])
Coordinates:
  * sex      (sex) <U1 'f' 'u' 'm'
  * age      (age) int64 1 2 3 6


# Test Cases

## Unknown Test case

In [ ]:


sr,ar,br,wr = ["m","f"],range(0,11),range(1,17),range(10,30)
coords = {"sex":sr,"age":ar,"BL":br,"week":wr}

z = np.zeros(list(map(len,[sr,ar,br,wr])),dtype="int64")


print(z.shape)


for sj,s in enumerate(sr):
    si = {"m":1,"f":2}.get(s,0)
    for aj,age in enumerate(ar):
        ai = si*1000+age
        for bj,bl in enumerate(br):
            bi = ai*1000+bl
            for wj,week in enumerate(wr):
                wi = bi*10000+week
                z[sj,aj,bj,wj] = wi
                
a = xr.DataArray(z,dims=coords.keys(),coords=coords)
#print(a)     

In [ ]:
a = slice(3,9,2)
c = slice(None,3)
print(a,c)

b = tt.cast(np.arange(160).reshape(20,4,2),"int64")

d = tt.cast([True,False,True,False],"bool")
print(tt.flatten(b[a,d]).eval()[c])

In [ ]:
slice(10,20,1)+slice(30,35,2)